# Generated by Django 2.2.4 on 2020-03-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=20, verbose_name='Merchant Name')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, verbose_name='Store Name')),
                ('store_address', models.CharField(max_length=50, verbose_name='Store Address')),
                ('s_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('s_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stores', to='plan.Merchants')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('item_price', models.FloatField(default=0, verbose_name='Item Price')),
                ('item_description', models.TextField(blank=True, verbose_name='Item Description')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_items', to='plan.Merchants')),
            ],
        ),
    ]
