# Generated by Django 2.2.4 on 2020-03-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Merchants',
            new_name='Merchant',
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
