# Generated by Django 2.2.4 on 2020-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=300, verbose_name='Item Name'),
        ),
    ]
